
---
title: "Figure3"
author: "Alexis Marshall"
date: "2 September 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
#library("vegan")
library("ggplot2")
library("phyloseq")
library("ggpubr")

```



```{r}
theme_Publication <- function(base_size=10, base_family="Courier") {
  library(grid)
  library(ggthemes)
  (theme_foundation(base_size=base_size, base_family=base_family)
    + theme(plot.title = element_text(face = "bold",
                                      size = rel(1.2), hjust = 0.5),
            text = element_text(),
            panel.background = element_rect(colour = NA),
            plot.background = element_rect(colour = NA),
            panel.border = element_rect(colour = NA),
            axis.title = element_text(face = "bold",size = rel(1)),
            axis.title.y = element_text(angle=90,vjust =2),
            axis.title.x = element_text(vjust = -0.2),
            axis.text = element_text(), 
            axis.line = element_line(colour="black"),
            axis.ticks = element_line(),
            panel.grid.major = element_blank(),
            panel.grid.minor = element_blank(),
            legend.key = element_rect(colour = NA),
            legend.position = "right",
            legend.direction = "vertical",
            legend.key.size= unit(0.2, "cm"),
            legend.margin = unit(1, "cm"),
            legend.title = element_blank(),
            plot.margin=unit(c(10,5,5,5),"mm"),
            strip.background=element_rect(colour="#f0f0f0",fill="#f0f0f0"),
            strip.text = element_text(face="bold")
    ))
  
}

scale_fill_Publication <- function(...){
  library(scales)
  discrete_scale("fill","Publication",manual_pal(values = c("#FFCC99", "#fdb462","#386cb0","#7fc97f","#ef3b2c","#662506","#a6cee3","#fb9a99","#984ea3","#ffff33")), ...)
  
}

scale_colour_Publication <- function(...){
  library(scales)
  discrete_scale("colour","Publication",manual_pal(values = c("#FFCC99", "#fdb462","#386cb0","#7fc97f","#ef3b2c","#662506","#a6cee3","#fb9a99","#984ea3","#ffff33")), ...)
  
}

```


```{r}
# Make phyloseq object OTU table using the flipped McMurdo OTU table

McMurdo_ASV <- t(read.csv("Phyloseq/ASVs_counts.csv", header = TRUE, sep=",", row.names=1))
McMurdo_ASV = otu_table(McMurdo_ASV, taxa_are_rows = FALSE) #

# Import taxonomic information into phyloseq
McMurdoSound_taxa <- as.matrix(read.csv("Phyloseq/ASVs_taxonomy.csv", sep=",", row.names=1))
TAXTABLE1 = tax_table(McMurdoSound_taxa)

# Import sample data
McMurdoSound_sample <- read.csv("Phyloseq/sample_info.csv", sep=",", row.names=1)
McMurdoSound_sampledata = sample_data(McMurdoSound_sample)

# import phylogenetic tree. Use the "greengreens" import function as MUSCLE outputs semi-colon dilimited too. 
McMurdoSound_tree <- read_tree_greengenes("Phyloseq/input.tre")

#McMurdo_ICEonly <- phyloseq(McMurdo_ASV, McMurdoSound_sampledata, TAXTABLE1, McMurdoSound_tree)

McMurdo_phyloseq <- phyloseq(McMurdo_ASV, McMurdoSound_sampledata, TAXTABLE1, McMurdoSound_tree)

McMurdo_ICEonly <- subset_samples(McMurdo_phyloseq, sample!="JWM" & sample!="CE16")
McMurdo_ICEonly_ASVs = as(otu_table(McMurdo_ICEonly), "matrix")
McMurdo_ICEonly_sampledata = as(sample_data(McMurdo_ICEonly), "matrix")

```


```{r, warning=FALSE, message=FALSE, fig.width=8, fig.height=5}

rowSums(otu_table(McMurdo_ICEonly))

McMurdo_ASV_FIG3 = transform_sample_counts(McMurdo_ICEonly, function(x) x / sum(x)*100)
rowSums(otu_table(McMurdo_ASV_FIG3))

sample_data(McMurdo_ASV_FIG3)


ordu1 = ordinate(McMurdo_ASV_FIG3, "PCoA", "unifrac", weighted=TRUE)
FIG3A = plot_ordination(McMurdo_ASV_FIG3, ordu1, color="sample", shape="sample")
FIG3A = FIG3A + scale_shape_manual(values=c(16, 15, 17, 18)) + geom_point(size=20, alpha=1)
FIG3A = FIG3A + scale_fill_brewer(palette="Set2")
FIG3A = FIG3A + theme_Publication(base_size = 45) + theme(legend.title = element_blank()) + theme(plot.margin = unit(c(0,200,0,0), "pt"))
FIG3A

# ANOSIM
site_group = get_variable(McMurdo_ASV_FIG3, "sample")
site_wunifrac_anosim = anosim(phyloseq::distance(McMurdo_ASV_FIG3, "wunifrac"), site_group)
site_wunifrac_anosim



#Call:
#anosim(x = phyloseq::distance(McMurdo_ASV_FIG3, "wunifrac"),      grouping = site_group) 
#Dissimilarity: 

#ANOSIM statistic R:     1 
#      Significance: 0.011 

#Permutation: free
#Number of permutations: 999


ordu2 = ordinate(McMurdo_ASV_FIG3, "PCoA", "unifrac", weighted=FALSE)
FIG3B = plot_ordination(McMurdo_ASV_FIG3, ordu2, color="sample", shape="sample")
FIG3B = FIG3B + scale_shape_manual(values=c(16, 15, 17, 18)) + geom_point(size=20, alpha=1)
FIG3B = FIG3B  + scale_fill_brewer(palette="Set2")
FIG3B = FIG3B + theme_Publication(base_size = 45) + theme(legend.title = element_blank()) 
FIG3B

# ANOSIM
site_group = get_variable(McMurdo_ASV_FIG3, "sample")
site_unifrac_anosim = anosim(phyloseq::distance(McMurdo_ASV_FIG3, "unifrac"), site_group)
site_unifrac_anosim


#Call:
#anosim(x = phyloseq::distance(McMurdo_ASV_FIG3, "unifrac"), grouping = site_group) 
#Dissimilarity: 

#ANOSIM statistic R: 0.9937 
#      Significance: 0.01 

#Permutation: free
#Number of permutations: 999


figure3 = (FIG3A /FIG3B) + plot_annotation(tag_levels = 'A') & theme(plot.tag = element_text(size=100))

ggexport(figure3, filename ="Figure_3.tiff", width = 5000, height = 6000, res = 300)


```
