---
title: "Figure2"
author: "Alexis Marshall"
date: "2 September 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library("phyloseq")
library("ggplot2")
library("vegan")
```

```{r}
theme_Publication <- function(base_size=10, base_family="Courier") {
  library(grid)
  library(ggthemes)
  (theme_foundation(base_size=base_size, base_family=base_family)
    + theme(plot.title = element_text(face = "bold",
                                      size = rel(1.2), hjust = 0.5),
            text = element_text(),
            panel.background = element_rect(colour = NA),
            plot.background = element_rect(colour = NA),
            panel.border = element_rect(colour = NA),
            axis.title = element_text(face = "bold",size = rel(1)),
            axis.title.y = element_text(angle=90,vjust =2),
            axis.title.x = element_text(vjust = -0.2),
            axis.text = element_text(), 
            axis.line = element_line(colour="black"),
            axis.ticks = element_line(),
            panel.grid.major = element_blank(),
            panel.grid.minor = element_blank(),
            legend.key = element_rect(colour = NA),
            legend.position = "right",
            legend.direction = "vertical",
            legend.key.size= unit(0.2, "cm"),
            legend.margin = unit(1, "cm"),
            legend.title = element_blank(),
            plot.margin=unit(c(10,5,5,5),"mm"),
            strip.background=element_rect(colour="#f0f0f0",fill="#f0f0f0"),
            strip.text = element_text(face="bold")
    ))
  
}

scale_fill_Publication <- function(...){
  library(scales)
  discrete_scale("fill","Publication",manual_pal(values = c("#FFCC99", "#fdb462","#386cb0","#7fc97f","#ef3b2c","#662506","#a6cee3","#fb9a99","#984ea3","#ffff33")), ...)
  
}

scale_colour_Publication <- function(...){
  library(scales)
  discrete_scale("colour","Publication",manual_pal(values = c("#FFCC99", "#fdb462","#386cb0","#7fc97f","#ef3b2c","#662506","#a6cee3","#fb9a99","#984ea3","#ffff33")), ...)
  
}

```

# Make phyloseq object with Taylor Valley samples
```{r, echo=T, results='hide', message = FALSE, warnings=FALSE}

# Make phyloseq object OTU table using the flipped McMurdo OTU table

McMurdo_ASV <- t(read.csv("TaylorValleyfiles/ASVs_counts.csv", header = TRUE, sep=",", row.names=1))
McMurdo_ASV = otu_table(McMurdo_ASV, taxa_are_rows = FALSE) #

# Import taxonomic information into phyloseq
McMurdoSound_taxa <- as.matrix(read.csv("TaylorValleyfiles/ASVs_taxonomy_no_chloro_020921.csv", sep=",", row.names=1))
TAXTABLE1 = tax_table(McMurdoSound_taxa)

# Import sample data
McMurdoSound_sample <- read.csv("TaylorValleyfiles/sample_info_030921.csv", sep=",", row.names=1)
McMurdoSound_sampledata = sample_data(McMurdoSound_sample)

# import phylogenetic tree. Use the "greengreens" import function as MUSCLE outputs semi-colon dilimited too. 
McMurdoSound_tree <- read_tree_greengenes("TaylorValleyfiles/NZTABS_CENH_tree.phy")
taxa_names(McMurdoSound_tree) <- sub(">.*", "", taxa_names(McMurdoSound_tree))


McMurdo_phyloseq <- phyloseq(McMurdo_ASV, McMurdoSound_sampledata, TAXTABLE1, McMurdoSound_tree)
McMurdo_phyloseq

```

#Barplot - phylum
```{r, fig.width=20, fig.height=15, warning=FALSE, message=FALSE}

sample_data(McMurdo_phyloseq)$sample = factor(sample_data(McMurdo_phyloseq)$sample, levels = c("CE","NH","JM","TV"))
McMurdo_ASV_SupFIG2a <- tax_glom(McMurdo_phyloseq, "Phylum")
McMurdo_ASV_SupFIG2a = transform_sample_counts(McMurdo_ASV_SupFIG2a, function(x) x / sum(x)*100)

top10phylum <- names(sort(taxa_sums(McMurdo_ASV_SupFIG2a), TRUE)[1:10])
McMurdoTV.top10phylum <- prune_taxa(top10phylum , McMurdo_ASV_SupFIG2a)

SupFig2a <- plot_bar(McMurdoTV.top10phylum, x="ID", y="Abundance", fill="Phylum")   + scale_x_discrete(limits=c("CE1", "CE2", "CE3", "CE4",
                                                                                         "NH1","NH2","NH3","NH4","NH5",
                                                                                         "SM1","SM2","SM3","SM4",
                                                                                         "TV1","TV2","TV3","TV4"))

SupFig2a = SupFig2a + theme_Publication(base_size = 30) + theme(axis.text.x = element_text(size=30, angle = 90)) + theme(axis.text.y = element_text(size=30)) + theme(axis.title.x = element_blank()) + theme(axis.title.y = element_text(size=40))
SupFig2a= SupFig2a+ theme(legend.text = element_text(size = 30, face = "italic"))  + scale_fill_brewer(palette="Set3") + theme(legend.title = element_text(size = 40))
SupFig2a= SupFig2a+ theme(legend.key.size = unit(1.5, "cm"), legend.key.width = unit(0.8,"cm"))
SupFig2a= SupFig2a+ theme(axis.title.y = element_text(face="plain")) + ylab("Relative abundance (%)")


```



```{r, fig.width=20, fig.height=15, warning=FALSE, message=FALSE}

McMurdo_ASV_SupFig2b <- tax_glom(McMurdo_phyloseq, "Class")
McMurdo_ASV_SupFig2b = transform_sample_counts(McMurdo_ASV_SupFig2b, function(x) x / sum(x)*100)

top10class <- names(sort(taxa_sums(McMurdo_ASV_SupFig2b), TRUE)[1:10])
McMurdoTV.top10class <- prune_taxa(top10class, McMurdo_ASV_SupFig2b)

SupFig2b <- plot_bar(McMurdoTV.top10class, x="ID", y="Abundance", fill="Class")  + scale_x_discrete(limits=c("CE1", "CE2", "CE3", "CE4",
                                                                                         "NH1","NH2","NH3","NH4","NH5",
                                                                                         "SM1","SM2","SM3","SM4",
                                                                                         "TV1","TV2","TV3","TV4"))

SupFig2b = SupFig2b + theme_Publication(base_size = 30) + theme(axis.text.x = element_text(size=30, angle = 90)) + theme(axis.text.y = element_text(size=30)) + theme(axis.title.x = element_blank()) + theme(axis.title.y = element_text(size=40))
SupFig2b = SupFig2b + theme(legend.text = element_text(size = 30, face = "italic")) + scale_fill_brewer(palette="Set3") + theme(legend.title = element_text(size = 40))
SupFig2b = SupFig2b + theme(legend.key.size = unit(1.5, "cm"), legend.key.width = unit(0.8,"cm"))
SupFig2b = SupFig2b + theme(axis.title.y = element_text(face="plain")) + ylab("Relative abundance (%)")

```


```{r, warning=FALSE, message=FALSE, fig.width=8, fig.height=5}

rowSums(otu_table(McMurdo_phyloseq))

McMurdo_ASV_SupFig2c = transform_sample_counts(McMurdo_phyloseq, function(x) x / sum(x)*100)
rowSums(otu_table(McMurdo_ASV_SupFig2c))

sample_data(McMurdo_ASV_SupFig2c)


ordu2 = ordinate(McMurdo_ASV_SupFig2c, "PCoA", "unifrac")
SupFig2c = plot_ordination(McMurdo_ASV_SupFig2c, ordu2, color="sample", shape="sample")
SupFig2c = SupFig2c + scale_shape_manual(values=c(16, 15, 17, 18)) + geom_point(size=20, alpha=1)
SupFig2c = SupFig2c  + scale_fill_brewer(palette="Set2")
SupFig2c = SupFig2c + theme_Publication(base_size = 45) + theme(legend.title = element_blank()) 
SupFig2c

# ANOSIM
site_group = get_variable(McMurdo_ASV_SupFig2c, "sample")
site_unifrac_anosim = anosim(phyloseq::distance(McMurdo_ASV_SupFig2c, "unifrac"), site_group)
site_unifrac_anosim


#anosim(x = phyloseq::distance(McMurdo_ASV_SupFig2c, "unifrac"),      grouping = site_group) 
#Dissimilarity: 

#ANOSIM statistic R: 0.9616 
#      Significance: 0.001 

#Permutation: free
#Number of permutations: 999


```





#Calculate Breakaway alpha diversity
```{r}

richness_McMurdoSound_d <- breakaway(McMurdo_phyloseq) 
richness_McMurdoSound_d = summary(richness_McMurdoSound_d)
alpha_breakaway <- cbind(richness_McMurdoSound_d, McMurdoSound_sampledata)

richness_McMurdoSound_e <- sample_shannon(McMurdo_phyloseq)
richness_McMurdoSound_e = summary(richness_McMurdoSound_e)
shannon_breakaway <- cbind(richness_McMurdoSound_e, McMurdoSound_sampledata)

```


#Plot taxonomic and phylogenetic alpha diversity
```{r, fig.height= 25, fig.width= 10, warning=FALSE, message=FALSE}}

SupFig2d <- ggplot(alpha_breakaway, aes(x=sample, y=estimate, fill =sample, shape=sample)) + geom_boxplot(lwd=1.2) + geom_dotplot(binaxis='y', stackdir='center', dotsize=1.5) + labs(x="Sample", y = "Species richness") + theme_classic()
SupFig2d = SupFig2d + scale_x_discrete(limits=c("CE", "NH", "SM", "TV"))
SupFig2d = SupFig2d + scale_shape_manual(values=c(16, 15,16, 15))
SupFig2d = SupFig2d + theme(legend.position="none") + theme(axis.title.y = element_text(size = rel(2.5), angle = 90))
SupFig2d = SupFig2d + theme(axis.title.x = element_blank()) + theme(axis.text = element_text(size = 30)) + theme(axis.line = element_line(size = 1.2)) + theme(axis.title.y = element_text(size = 30))



all_breakaway <- alpha_breakaway %>%
  select(sample, estimate) %>%
  group_by(sample) %>%
  summarize(
    avg_abundance = mean(estimate), sd_abundance  = sd(estimate)
    ) %>% arrange(desc(avg_abundance))


all_breakaway %>% kbl(caption = "alpha_breakaway", digits = 2) %>%
  kable_classic(full_width = F, html_font = "Arial")





SupFig2e <-ggplot(shannon_breakaway, aes(x=sample, y=estimate, fill =sample, shape=sample)) + geom_boxplot(lwd=1.2) +
  geom_dotplot(binaxis='y', stackdir='center', dotsize=1.5) +
  labs(x="Sample", y = "Shannon diversity")+
  theme_classic()
SupFig2e = SupFig2e + scale_x_discrete(limits=c("CE", "NH", "SM", "TV"))
SupFig2e = SupFig2e + scale_shape_manual(values=c(16, 15,16, 15))
SupFig2e = SupFig2e + theme(legend.position="none") + theme(axis.title.y = element_text(size = rel(2.5), angle = 90))
SupFig2e = SupFig2e + theme(axis.title.x = element_blank()) + theme(axis.text = element_text(size = 30)) + theme(axis.line = element_line(size = 1.2)) + theme(axis.title.y = element_text(size = 30))




all_shannon <- shannon_breakaway %>%
  select(sample, estimate) %>%
  group_by(sample) %>%
  summarize(
    avg_abundance = mean(estimate), sd_abundance  = sd(estimate)
    ) %>% arrange(desc(avg_abundance))


all_shannon %>% kbl(caption = "shannon_breakaway", digits = 2) %>%
  kable_classic(full_width = F, html_font = "Arial")





```


```{r}


SupFig2 = (SupFig2a + SupFig2a)/(SupFig2c + SupFig2d + SupFig2e) + plot_layout(heights = unit(c(20, 20), c('cm', 'null'))) + plot_annotation(tag_levels = 'A') & theme(plot.tag = element_text(size=80))

ggexport(SupFig2, filename ="SuppFigure_2.tiff", width = 10000, height = 6000, res = 300)



```



```{r}
phylumabundance <- McMurdo_phyloseq %>%
  tax_glom(taxrank = "Order") %>%                     # agglomerate at phylum level
  transform_sample_counts(function(x) {x/sum(x)} * 100 ) %>% # Transform to rel. abundance
  psmelt() %>%   
  group_by(Order) %>%
  arrange(Abundance)


all <- phylumabundance %>%
  select(Order, sample, Abundance, ID) %>%
  group_by(Order, sample) %>%
  summarize(
    avg_abundance = mean(Abundance), sd_abundance  = sd(Abundance)
    ) %>%
  filter(avg_abundance > 0.01) %>% arrange(desc(avg_abundance))


all %>% kbl(caption = "Order", digits = 1) %>%
  kable_classic(full_width = F, html_font = "Arial")


```

```{r}
phylumabundance <- McMurdo_phyloseq %>%
  tax_glom(taxrank = "Phylum") %>%                     # agglomerate at phylum level
  transform_sample_counts(function(x) {x/sum(x)} * 100 ) %>% # Transform to rel. abundance
  psmelt() %>%   
  group_by(Phylum) %>%
  arrange(Abundance)


all <- phylumabundance %>%
  select(Phylum, sample, Abundance, ID) %>%
  group_by(Phylum, sample) %>%
  summarize(
    avg_abundance = mean(Abundance), sd_abundance  = sd(Abundance)
    ) %>%
  filter(avg_abundance > 0.01) %>% arrange(desc(avg_abundance))


all %>% kbl(caption = "Phylum", digits = 1) %>%
  kable_classic(full_width = F, html_font = "Arial")


```

```{r}
phylumabundance <- McMurdo_phyloseq %>%
  tax_glom(taxrank = "Class") %>%                     # agglomerate at phylum level
  transform_sample_counts(function(x) {x/sum(x)} * 100 ) %>% # Transform to rel. abundance
  psmelt() %>%   
  group_by(Class) %>%
  arrange(Abundance)


all <- phylumabundance %>%
  select(Class, sample, Abundance, ID) %>%
  group_by(Class, sample) %>%
  summarize(
    avg_abundance = mean(Abundance), sd_abundance  = sd(Abundance)
    ) %>%
  filter(avg_abundance > 0.01) %>% arrange(desc(avg_abundance))


all %>% kbl(caption = "Class", digits = 1) %>%
  kable_classic(full_width = F, html_font = "Arial")


```